# from sqlalchemy import *
#
# from utils.db.db_config import get_db_engine
#
# meta = MetaData()
# engine = get_db_engine()
#
# opera_occ_model = Table(
#     'opera_occ', meta,
#     Column('id', Integer, primary_key=True, autoincrement=True),
#     Column('propertyCode', String(20)),
#     Column('pullDateId', String(20)),
#     Column('REVENUE', String(55)),
#     Column('NO_ROOMS', String(55)),
#     Column('IND_DEDUCT_ROOMS', String(55)),
#     Column('IND_NON_DEDUCT_ROOMS', String(55)),
#     Column('GRP_DEDUCT_ROOMS', String(55)),
#     Column('GRP_NON_DEDUCT_ROOMS', String(55)),
#     Column('NO_PERSONS', String(55)),
#     Column('ARRIVAL_ROOMS', String(55)),
#     Column('DEPARTURE_ROOMS', String(55)),
#     Column('COMPLIMENTARY_ROOMS', String(55)),
#     Column('HOUSE_USE_ROOMS', String(55)),
#     Column('DAY_USE_ROOMS', String(55)),
#     Column('NO_SHOW_ROOMS', String(55)),
#     Column('INVENTORY_ROOMS', String(55)),
#     Column('CONSIDERED_DATE', String(55)),
#     Column('CHAR_CONSIDERED_DATE', String(55)),
#     Column('IND_DEDUCT_REVENUE', String(55)),
#     Column('IND_NON_DEDUCT_REVENUE', String(55)),
#     Column('GRP_NON_DEDUCT_REVENUE', String(55)),
#     Column('GRP_DEDUCT_REVENUE', String(55)),
#     Column('OWNER_ROOMS', String(55)),
#     Column('FF_ROOMS', String(55)),
#     Column('CF_OOO_ROOMS', String(55)),
#     Column('CF_CALC_OCC_ROOMS', String(55)),
#     Column('CF_CALC_INV_ROOMS', String(55)),
#     Column('CF_AVERAGE_ROOM_RATE', String(55)),
#     Column('CF_OCCUPANCY', String(55)),
#     Column('CF_IND_DED_REV', String(55)),
#     Column('CF_IND_NON_DED_REV', String(55)),
#     Column('CF_BLK_DED_REV', String(55)),
#     Column('CF_BLK_NON_DED_REV', String(55))
# )
#
# marriott_forecast_model = Table(
#     'marriott_forecast', meta,
#     Column('id', Integer, primary_key=True, autoincrement=True),
#     Column('propertyCode', String(55)),
#     Column('pullDateId', BIGINT),
#     Column('ArrivalDate', String(55)),
#     Column('ArrivalDay', String(55)),
#     Column('WEindicator', String(55)),
#     Column('Capacity', String(55)),
#     Column('DaysOut', String(55)),
#     Column('SysRemDem', String(55)),
#     Column('RemDemSTLY', String(55)),
#     Column('AppliedRemDem', String(55)),
#     Column('UserOverride', String(55)),
#     Column('Event', String(55)),
#     Column('OYv2TotalHotelOccupancy', String(55)),
#     Column('TotalAvailableTransientSupply', String(55)),
#     Column('TotalTransientBooked', String(55)),
#     Column('TotalTransientBookedSTLY', String(55)),
#     Column('AdditionalDemand', String(55)),
#     Column('AdditionalDemandSTLY', String(55)),
#     Column('TotalTransientDemand', String(55)),
#     Column('TotalTransientDemandSTLY', String(55)),
#     Column('AllotmentForecast', String(55)),
#     Column('AllotmentRoomsSold', String(55)),
#     Column('OutofOrder', String(55)),
#     Column('GroupRoomBlockAuthorized', String(55)),
#     Column('GroupBooked', String(55)),
#     Column('OYv2GroupProj', String(55)),
#     Column('ContractRoomBlockAuthorized', String(55)),
#     Column('ContractBooked', String(55)),
#     Column('OYv2ContractProj', String(55)),
#     Column('ComplimentaryBookedTY', String(55)),
#     Column('RemDemPremiumRetailTY', String(55)),
#     Column('RemDemPremiumRetailTYPer', String(55)),
#     Column('PremiumRetailTY', String(55)),
#     Column('RemDemPremiumRetailSTLY', String(55)),
#     Column('RemDemPremiumRetailSTLYPer', String(55)),
#     Column('PremiumRetailSTLY', String(55)),
#     Column('RemDemStandardRetailTY', String(55)),
#     Column('RemDemStandardRetailTYPer', String(55)),
#     Column('StandardRetailTY', String(55)),
#     Column('RemDemStandardRetailSTLY', String(55)),
#     Column('RemDemStandardRetailSTLYPer', String(55)),
#     Column('StandardRetailSTLY', String(55)),
#     Column('RemDemSpecialCorporateLRATY', String(55)),
#     Column('RemDemSpecialCorporateLRATYPer', String(55)),
#     Column('SpecialCorporateLRATY', String(55)),
#     Column('RemDemSpecialCorporateLRASTLY', String(55)),
#     Column('RemDemSpecialCorporateLRASTLYPer', String(55)),
#     Column('SpecialCorporateLRASTLY', String(55)),
#     Column('RemDemRewardRedemptionTY', String(55)),
#     Column('RemDemRewardRedemptionTYPer', String(55)),
#     Column('RewardRedemptionTY', String(55)),
#     Column('RemDemRewardRedemptionSTLY', String(55)),
#     Column('RemDemRewardRedemptionSTLYPer', String(55)),
#     Column('RewardRedemptionSTLY', String(55)),
#     Column('RemDemPolicyDrivenTY', String(55)),
#     Column('RemDemPolicyDrivenTYPer', String(55)),
#     Column('PolicyDrivenTY', String(55)),
#     Column('RemDemPolicyDrivenSTLY', String(55)),
#     Column('RemDemPolicyDrivenSTLYPer', String(55)),
#     Column('PolicyDrivenSTLY', String(55)),
#     Column('RemDemGovtMilitaryTY', String(55)),
#     Column('RemDemGovtMilitaryTYPer', String(55)),
#     Column('GovtMilitaryTY', String(55)),
#     Column('RemDemGovtMilitarySTLY', String(55)),
#     Column('RemDemGovtMilitarySTLYPer', String(55)),
#     Column('GovtMilitarySTLY', String(55)),
#     Column('RemDemRetailTiedDiscountTY', String(55)),
#     Column('RemDemRetailTiedDiscountTYPer', String(55)),
#     Column('RetailTiedDiscountTY', String(55)),
#     Column('RemDemRetailTiedDiscountSTLY', String(55)),
#     Column('RemDemRetailTiedDiscountSTLYPer', String(55)),
#     Column('RetailTiedDiscountSTLY', String(55)),
#     Column('RemDemFixedDiscountTY', String(55)),
#     Column('RemDemFixedDiscountTYPer', String(55)),
#     Column('FixedDiscountTY', String(55)),
#     Column('RemDemFixedDiscountSTLY', String(55)),
#     Column('RemDemFixedDiscountSTLYPer', String(55)),
#     Column('FixedDiscountSTLY', String(55)),
#     Column('RoomCollection1HurdleRevenue', String(55)),
#     Column('RoomCollection1TransientOTBTY', String(55)),
#     Column('RoomCollection1TransientOTBSTLY', String(55)),
#     Column('RoomCollection1RemDemTY', String(55)),
#     Column('RoomCollection1RemDemTYPer', String(55)),
#     Column('RoomCollection1RemDemSTLY', String(55)),
#     Column('RoomCollection1RemDemSTLYPer', String(55)),
#     Column('RoomCollection2HurdleRevenue', String(55)),
#     Column('RoomCollection2TransientOTBTY', String(55)),
#     Column('RoomCollection2TransientOTBSTLY', String(55)),
#     Column('RoomCollection2RemDemTY', String(55)),
#     Column('RoomCollection2RemDemTYPer', String(55)),
#     Column('RoomCollection2RemDemSTLY', String(55)),
#     Column('RoomCollection2RemDemSTLYPer', String(55)),
# )
#
# hotelkey_occ_model = Table(
#     'hotelkey_occ', meta,
#     Column('id', Integer, primary_key=True, autoincrement=True),
#     Column('propertyCode', String(55)),
#     Column('pullDateId', BIGINT),
#     Column('Date', String(55)),
#     Column('Property', String(55)),
#     Column('PFRZ', String(55)),
#     Column('FRZ', String(55)),
#     Column('TOD', String(55)),
#     Column('DOW', String(55)),
#     Column('GTD', String(55)),
#     Column('LOS', String(55)),
#     Column('CXL', String(55)),
#     Column('OO', String(55)),
#     Column('Hold', String(55)),
#     Column('Yieldable', String(55)),
#     Column('Sold', String(55)),
#     Column('BLK', String(55)),
#     Column('SD', String(55)),
#     Column('OccOTB', String(55)),
#     Column('OccPYClose', String(55)),
#     Column('OccPYVar', String(55)),
#     Column('ADROTB', String(55)),
#     Column('ADRPYClose', String(55)),
#     Column('ADRPYVar', String(55)),
#     Column('DiscPer', String(55)),
#     Column('Price1', String(55)),
#     Column('LT1', String(55)),
#     Column('Per1', String(55)),
#     Column('RM1', String(55)),
#     Column('Price2', String(55)),
#     Column('LT2', String(55)),
#     Column('Per2', String(55)),
#     Column('RM2', String(55)),
#     Column('Price3', String(55)),
#     Column('LT3', String(55)),
#     Column('Per3', String(55)),
#     Column('RM3', String(55)),
#     Column('Price4', String(55)),
#     Column('LT4', String(55)),
#     Column('Per4', String(55)),
#     Column('RM4', String(55)),
# )
# meta.create_all(engine)
