from sqlalchemy import *

meta = MetaData()

choice_res_model = Table(
    'choice_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Account', String(20)),
    Column('GuestName', Text()),
    Column('Arrive', String(10)),
    Column('Depart', String(10)),
    Column('Nights', String(20)),
    Column('Status', String(20)),
    Column('Rate', String(20)),
    Column('RateCode', String(20)),
    Column('Type', String(20)),
    Column('Room', String(20)),
    Column('Source', String(20)),
    Column('CRSConfNo', String(20)),
    Column('GTD', String(20)),
    Column('ReserveDate', String(20)),
    Column('ReserveTime', String(20)),
    Column('User', String(20)),
    Column('SharedAccount', String(20)),
    Column('TrackCode', String(20)),
    Column('Package', String(20)),
    Column('CancellationDate', String(10)),
    Column('CancellationTime', String(8)),
    Column('CXLUserID', String(255)),
)

choice_occ_model = Table(
    'choice_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('IDS_DATE', String(20)),
    Column('Day', String(20)),
    Column('Rooms', String(10)),
    Column('OOO', String(10)),
    Column('StayOver', String(20)),
    Column('Arrivals', String(20)),
    Column('DueOut', String(20)),
    Column('Available', String(20)),
    Column('GroupBlock', String(20)),
    Column('GroupPickedUp', String(20)),
    Column('TransNGTD', String(20)),
    Column('TransGTD', String(20)),
    Column('Occupied', String(20)),
    Column('OccPercent', String(20)),
    Column('RoomRev', String(20)),
    Column('RevPAR', String(20)),
    Column('ADR', String(20)),
    Column('Ppl', String(20))
)

choice_busi_model = Table(
    'choice_busi_on_books', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Date', String(20)),
    Column('TransientRooms', String(20)),
    Column('TransientPPL', String(10)),
    Column('GroupRooms', String(10)),
    Column('GroupPPL', String(20)),
    Column('DefiniteNotPickup', String(20)),
    Column('TentativeNotPickup', String(20)),
    Column('TotalOccupiedRooms', String(20)),
    Column('TotalPPL', String(20)),
    Column('Occ', String(20)),
    Column('COMPS', String(20)),
    Column('RoomRev', String(20)),
    Column('RevPar', String(20)),
    Column('ADR', String(20)),
)

choice_cancellation_model = Table(
    'choice_cancellation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('CancellationReason', String(55)),
    Column('CxlDate', String(55)),
    Column('Resv', String(55)),
    Column('RoomNights', String(55)),
    Column('RoomRev', String(55)),
)

choice_revenue_model = Table(
    'choice_revenue', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('IDS_RATE_CODE', String(55)),
    Column('RoomNights', String(55)),
    Column('RoomNightsPer', String(55)),
    Column('RoomRevenue', String(55)),
    Column('RoomRevenuePer', String(55)),
    Column('DailyAVG', String(55)),
    Column('PTDRoomNights', String(55)),
    Column('PTDRoomNightsPer', String(55)),
    Column('PTDRoomRevenue', String(55)),
    Column('PTDRoomRevenuePer', String(55)),
    Column('PTD_AVG', String(55)),
    Column('YTDRoomNights', String(55)),
    Column('YTDRoomNightsPer', String(55)),
    Column('YTDRoomRevenue', String(55)),
    Column('YTDRoomRevenuePer', String(55)),
    Column('YTD_AVG', String(55)),
)

choice_revenue_detail_model = Table(
    'choice_revenue_detail', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('IDS_DATE_DAY', String(55)),
    Column('RateCode', String(55)),
    Column('RoomNights', String(55)),
    Column('RoomNightsPer', String(55)),
    Column('RoomRevenue', String(55)),
    Column('RoomRevenuePer', String(55)),
    Column('DailyAVG', String(55)),
)

choice_group_pickup_detail_model = Table(
    'choice_group_pickup_detail', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('GroupName', String(55)),
    Column('GroupStatus', String(55)),
    Column('RollingCutOffDays', String(55)),
    Column('FixedCutOffDate', String(55)),
    Column('SalesManager', String(55)),
    Column('RoomType', String(55)),
    Column('BlockDate', String(55)),
    Column('OriginalBlock', String(55)),
    Column('CurrentBlock', String(55)),
    Column('GuaranteedArrivalsPickedUp', String(55)),
    Column('NonGuaranteedArrivalsPickedUp', String(55)),
    Column('TotalPickedUp', String(55)),
    Column('RoomsNotPickedUp', String(55)),
    Column('Revenue', String(55)),
    Column('ADR', String(55)),
)

choice_cancellation_list_model = Table(
    'choice_cancellation_list', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('Account', String(55)),
    Column('Guest_Name', String(55)),
    Column('Arrival_Group', String(55)),
    Column('Nights', String(55)),
    Column('Rate_Plan', String(55)),
    Column('GTD', String(55)),
    Column('Source', String(55)),
    Column('Rm_Type', String(55)),
    Column('Cxl_Code', String(55)),
    Column('Cxl_Date', String(55)),
    Column('Cxl_Clk', String(55)),
)

auto_clerk_res_model = Table(
    'auto_clerk_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('DateTime', String(20)),
    Column('Status', String(20)),
    Column('MyhmsConf', String(20)),
    Column('CRSConf', String(20)),
    Column('roomnumber', String(20)),
    Column('roomtype', String(20)),
    Column('rateplan', String(20)),
    Column('rate', String(20)),
    Column('Paytype', String(20)),
    Column('arrivaldate', String(20)),
    Column('departuredate', String(20)),
    Column('nights', String(20)),
    Column('guestlastname', String(20)),
    Column('guestfirstname', String(20)),
    Column('address1', Text),
    Column('address2', Text),
    Column('city', String(20)),
    Column('state', String(20)),
    Column('zip', String(20)),
    Column('country', String(20)),
    Column('phone', String(20)),
    Column('email', String(20)),
    Column('TotalRevenueforstay', String(20)),
    Column('RoomRevenueforstay', String(20)),
    Column('source', String(20)),
    Column('market', String(20)),
    Column('channel', String(20)),
    Column('companyName', String(20)),
    Column('drivingLicence', String(20))
)

auto_clerk_occ_model = Table(
    'auto_clerk_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Date', String(20)),
    Column('Rooms', String(20)),
    Column('Arrivals', String(20)),
    Column('StayOver', String(20)),
    Column('DepartToday', String(20)),
    Column('OccupRooms', String(20)),
    Column('UnusedGroupBlocks', String(20)),
    Column('Occup', String(20)),
    Column('A', String(20)),
    Column('C', String(20)),
    Column('I', String(20)),
    Column('RoomRevenue', String(20)),
    Column('ADR', String(20)),
    Column('REVPAR', String(20)),
    Column('OOORooms', String(20)),
    Column('UnusedAllotment', String(20)),
    Column('AvailRooms', String(20))
)

auto_clerk_group_block_summary_model = Table(
    'auto_clerk_group_block_summary', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('GroupBookingName', String(55)),
    Column('Confirmation', String(55)),
    Column('Arrive', String(55)),
    Column('Depart', String(55)),
    Column('Block', String(55)),
    Column('P_U', String(55)),
    Column('Diff', String(55)),
    Column('BlockedRevenue', String(55)),
    Column('PickedUpRevenue', String(55)),
    Column('CutoffDate', String(55)),
)

ihg_res_model = Table(
    'ihg_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('ConfirmationNumber', String(20)),
    Column('PriorityClubMember', String(20)),
    Column('GuestName', String(20)),
    Column('ArrivalDate', String(20)),
    Column('TransactionTime(GMT)', String(20)),
    Column('RateCode', String(20)),
    Column('RateCategory', String(20)),
    Column('Guaranteed', String(20)),
    Column('RoomType', String(20)),
    Column('ArrivalRoomRate', String(20)),
    Column('NumberofGuests', String(20)),
    Column('NumberofNights', String(20)),
    Column('NumberofRooms', String(20)),
    Column('PropertyName', String(20)),
    Column('ATLTM', String(20))
)

ihg_occ_model = Table(
    'ihg_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('BlackoutDates', String(20)),
    Column('blank', String(20)),
    Column('ClosedtoArrival', String(20)),
    Column('Date', String(20)),
    Column('DayofWeek', String(20)),
    Column('MaximumLOS', String(20)),
    Column('MinimumLOS', String(20)),
    Column('ReservationGuaranteeRequired', String(20)),
    Column('24Hourhold', String(20)),
    Column('AverageLeadTime', String(20)),
    Column('AverageLOS', String(20)),
    Column('CancelDue', String(20)),
    Column('CancelorNoShow', String(20)),
    Column('DepositDue', String(20)),
    Column('Deposit', String(20)),
    Column('Groupremaining', String(20)),
    Column('RoomslefttoSell', String(20)),
    Column('SpecialEventSpecialRequirement', String(20)),
    Column('Paceasofdate', String(20)),
    Column('AC', String(20)),
    Column('ActualroomssoldLY', String(20)),
    Column('ADR', String(20)),
    Column('BFR', String(20)),
    Column('Groupcommitted', String(20)),
    Column('Groupcontracted', String(20)),
    Column('GroupPickupasofdate', String(20)),
    Column('Grouppickup', String(20)),
    Column('Occ', String(20)),
    Column('OVB', String(20)),
    Column('Paceasofdate1', String(20)),
    Column('Paceasofdate2', String(20)),
    Column('Pickupasofdate', String(20)),
    Column('Pickupasofdate1', String(20)),
    Column('Roomssold', String(20)),
    Column('TotalRoomsCommitted', String(20)),
)

opera_occ_model = Table(
    'opera_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

opera_res_model = Table(
    'opera_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

opera_arrival_model = Table(
    'opera_arrival', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('REDEEM_FLAG_YN', String(255)),
    Column('MOBILE_REGSITERED_YN', String(255)),
    Column('TOTAL_STAYS_ACROSS_CHAIN', String(255)),
    Column('TOTAL_NIGHTS_ACROSS_CHAIN', String(255)),
    Column('EXTERNAL_REFERENCE', String(255)),
    Column('UPDATE_DATE', String(255)),
    Column('UPDATE_USER', String(255)),
    Column('DISP_ROOM_NO', String(255)),
    Column('RESV_COLOR', String(255)),
    Column('ROWNUM', String(255)),
    Column('IS_SHARED_YN', String(255)),
    Column('TRUNC_BEGIN', String(255)),
    Column('TRUNC_END', String(255)),
    Column('CONFIRMATION_NO', String(255)),
    Column('ARRIVAL', String(255)),
    Column('PRODUCTS', String(255)),
    Column('SHORT_RESV_STATUS', String(255)),
    Column('RESORT', String(255)),
    Column('FULL_NAME_NO_SHR_IND', String(255)),
    Column('ARRIVAL_TIME1', String(255)),
    Column('ARRIVAL_TRANSPORT_TYPE', String(255)),
    Column('FULL_NAME', String(255)),
    Column('NO_OF_ROOMS', String(255)),
    Column('ROOM_CATEGORY_LABEL', String(255)),
    Column('ARRIVAL_TIME', String(255)),
    Column('DEPARTURE_TIME', String(255)),
    Column('MARKET_CODE', String(255)),
    Column('RATE_CODE', String(255)),
    Column('DEPARTURE', String(255)),
    Column('VIP', String(255)),
    Column('GUARANTEE_CODE', String(255)),
    Column('BILL_TO_ADDRESS', String(255)),
    Column('PREFERRED_ROOM_TYPE', String(255)),
    Column('BEGIN_DATE', String(255)),
    Column('GROUP_ID', String(255)),
    Column('BLOCK_CODE', String(255)),
    Column('ORIGIN_OF_BOOKING', String(255)),
    Column('EFFECTIVE_RATE_AMOUNT', String(255)),
    Column('SPECIAL_REQUESTS', String(255)),
    Column('EXP_DATE', String(255)),
    Column('PAYMENT_METHOD', String(255)),
    Column('ADULTS', String(255)),
    Column('CHILDREN', String(255)),
    Column('PERSONS', String(255)),
    Column('DEPOSIT_PAID', String(255)),
    Column('ARRIVAL_CARRIER_CODE', String(255)),
    Column('COMPANY_NAME', String(255)),
    Column('CURRENCY_CODE', String(255)),
    Column('ROOM_NO', String(255)),
    Column('SHARE_AMOUNT', String(255)),
    Column('CREDIT_CARD_NUMBER', String(255)),
    Column('PHYSICAL_QUANTITY', String(255)),
    Column('RESV_NAME_ID', String(255)),
    Column('GUEST_NAME_ID', String(255)),
    Column('PREFERENCES', String(255)),
    Column('LAST_ROOM', String(255)),
    Column('SHARE_NAMES', String(255)),
    Column('ACCOMPANYING_YN', String(255)),
    Column('COMP_HOUSE', String(255)),
    Column('ACCOMPANYING_NAMES', String(255)),
    Column('EXTN_NUMBER', String(255)),
    Column('ADVANCE_CHECKED_IN_YN', String(255)),
    Column('SHOW_AWARDS_LAMP_YN', String(255)),
    Column('LIST_G_MEM_TYPE_LEVEL', String(255)),
    Column('LIST_G_INV_ITEMS', String(255)),
    Column('LIST_G_BILL_RESV', String(255)),
    Column('LIST_G_COMMENT_NAME_ID', String(255)),
    Column('LIST_G_RESERV_PROMO', String(255)),
    Column('LIST_G_DEPT_ID', String(255)),
    Column('LIST_G_DEP_DATE_CHANGE', String(255)),
    Column('LIST_G_COMMENT_RESV_NAME_ID', String(255)),
    Column('LIST_G_FIXED_CHARGES', String(255)),
    Column('LIST_G_AWARDS', String(255)),
    Column('NO_OF_STAYS', String(255)),
    Column('NO_OF_NIGHTS', String(255)),
    Column('COUNT_ROUTING', String(255)),
    Column('COUNT_COMMENTS', String(255)),
    Column('COUNT_RES_COMMENTS', String(255)),
    Column('COUNT_PROMOTIONS', String(255)),
    Column('COUNT_TRACES', String(255)),
    Column('COUNT_FIXED_CHARGES', String(255)),
    Column('COUNT_MEMBER_TYPE', String(255)),
    Column('COUNT_INVENTORY_ITEMS', String(255)),
    Column('COUNT_DEP_DATE_CHANGE', String(255)),
    Column('CF_COLOR_DESC', String(255)),
    Column('CF_DISPLAY_RECORD_01', String(255)),
    Column('CF_ADULTS', String(255)),
    Column('CF_CHILDREN', String(255)),
    Column('CF_NO_OF_ROOMS', String(255)),
)

synxis_cloud_reservation_model = Table(
    'synxis_cloud_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('Chain', String(55)),
    Column('Brand', String(55)),
    Column('Hotel', String(55)),
    Column('Confirm_No', String(55)),
    Column('Rez_Status_Desc', String(55)),
    Column('Status_Dt', String(55)),
    Column('Guest_Nm', String(55)),
    Column('Channel_Cd', String(55)),
    Column('Sec_Channel_Desc', String(55)),
    Column('Sub_Source', String(55)),
    Column('Sub_Src_CD', String(55)),
    Column('Location', String(55)),
    Column('Arrival_Dt', String(55)),
    Column('Depart_Dt', String(55)),
    Column('Nights_Qty', String(55)),
    Column('Override_Oversell', String(55)),
    Column('Room_Qty', String(55)),
    Column('Rate_Category_Name', String(55)),
    Column('Rate_Type_Code', String(55)),
    Column('Rez_Avg_Rate_Amt', String(55)),
    Column('Onshore_Rate_Type_Code', String(55)),
    Column('Onshore_Rez_Avg_Rate_Amt', String(55)),
    Column('Room_Type_Code', String(55)),
    Column('Record_Locator', String(55)),
    Column('Booker_Loyalty_Program_Level_List', String(55)),
    Column('Loyalty_Type', String(55)),
    Column('Loyalty_Program', String(55)),
    Column('Loyalty_Number', String(55)),
    Column('Loyalty_Level_Code', String(55)),
    Column('Loyalty_Level_Name', String(55)),
    Column('Loyalty_Points_Payment', String(55)),
    Column('Payment_Typ', String(55)),
    Column('VCC_Authorization_Amount', String(55)),
    Column('VCC_Currency_Code', String(55)),
    Column('VCC_Payment_Model', String(55)),
    Column('VCC_Card_Activation_Start', String(55)),
    Column('VCC_Card_Activation_End', String(55)),
    Column('Direct_Bill_Account_Number', String(55)),
    Column('Direct_Bill_Project_Number', String(55)),
    Column('Total_Points_Pymnt', String(55)),
    Column('Points_Refund', String(55)),
    Column('Total_Cash_Pymnt', String(55)),
    Column('Pay_At_Property', String(55)),
    Column('Cash_Refund', String(55)),
    Column('Total_Price_For_Adult', String(55)),
    Column('Total_Adult_Occupancy', String(55)),
    Column('Total_Price_For_Child_Age_Group1', String(55)),
    Column('Total_Child_Occupancy_For_Age_Group1', String(55)),
    Column('Total_Price_For_Child_Age_Group2', String(55)),
    Column('Total_Child_Occupancy_For_Age_Group2', String(55)),
    Column('Total_Price_For_Child_Age_Group3', String(55)),
    Column('Total_Child_Occupancy_For_Age_Group3', String(55)),
    Column('Total_Price_For_Child_Age_Group4', String(55)),
    Column('Total_Child_Occupancy_For_Age_Group4', String(55)),
    Column('Total_Price_For_Child_Age_Group5', String(55)),
    Column('Total_Child_Occupancy_For_Age_Group5', String(55)),
    Column('Total_Price_For_Child_Unknown_Age_Group', String(55)),
    Column('Total_Child_Occupancy_For_Unknown_Age_Group', String(55)),
    Column('Share_With', String(55)),
    Column('Channel_Connect_Confirm_NO', String(55)),
    Column('PMS_Confirm_Code', String(55)),
    Column('Original_Room_Type_Code', String(55)),
    Column('Original_Rm_Typ_Nm', String(55)),
    Column('Template_Code', String(55)),
    Column('Template_Name', String(55)),
    Column('Blacklist_Reason', String(55)),
    Column('Visa_Information', String(55)),
    Column('Installment_Amount', String(55)),
    Column('Number_of_Installments', String(55)),
    Column('Interest_Amount', String(55)),
    Column('Interest_Rate_Percentage', String(55)),
    Column('Total_Installment_Amount', String(55)),
    Column('Rate_Credential_ID', String(55)),
    Column('Trace_Date', String(55)),
    Column('Trace_Completion_Flag', String(55)),
    Column('Trace_Completion_Date', String(55)),
    Column('Trace_Text', String(55)),
    Column('RM_Upgrade_Reason_CD', String(55)),
    Column('Room_Upsell', String(55)),
    Column('Room_To_Charge', String(55)),
    Column('Onhold_Duration', String(55)),
    Column('AutoCancel_ReleaseDateTime_ScheduledOrActual', String(55)),
    Column('Commission_Cd', String(55)),
    Column('Comm_Percent_Override_List', String(55)),
    Column('Coupon_Offer', String(55)),
    Column('Coupon_Discount_Total', String(55)),
    Column('Promotion', String(55)),
    Column('Promo_Discount', String(55)),
    Column('Maximum_Discount_Applied', String(55)),
    Column('Paynow_Discount', String(55)),
)

synxis_cloud_forecast_model = Table(
    'synxis_cloud_forecast', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('cal_dt', String(55)),
    Column('Total_Rooms', String(55)),
    Column('OOO_OOI', String(55)),
    Column('rentable_rooms', String(55)),
    Column('Rooms_Sold', String(55)),
    Column('total_stayovers', String(55)),
    Column('total_due_out', String(55)),
    Column('Total_Reservations', String(55)),
    Column('day_use_in_house', String(55)),
    Column('gtd', String(55)),
    Column('non_gtd', String(55)),
    Column('Not_Picked_Up', String(55)),
    Column('Left_To_Sell', String(55)),
    Column('occ_per', String(55)),
    Column('Total_Room_Revenue', String(55)),
    Column('ADR', String(55)),
    Column('Adult_Child', String(55)),
    Column('Sum_Total_Rooms', String(55)),
    Column('SumOOO_OOI', String(55)),
    Column('Sum_Rentable_Rooms', String(55)),
    Column('Sum_Rooms_Sold', String(55)),
    Column('Sum_Stayovers', String(55)),
    Column('Sum_Checkouts', String(55)),
    Column('Sum_Arrivals', String(55)),
    Column('Sum_Day_Use', String(55)),
    Column('SumGtd', String(55)),
    Column('SumNonGtd', String(55)),
    Column('Sum_GroupsRoomsNotPickedUp', String(55)),
    Column('Sum_Rooms_Left_To_Sell', String(55)),
    Column('Sum_RoomsOccupied_Percentage', String(55)),
    Column('SumTotalRoomRevenue', String(55)),
    Column('Sum_ADR', String(55)),
    Column('SUM_ADULT_CHILD', String(55)),
)

synxis_cloud_revenue_recap_model = Table(
    'synxis_cloud_revenue_recap', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('report_type', String(55)),
    Column('report_type_values', String(55)),
    Column('Room_Nights', String(55)),
    Column('Room', String(55)),
    Column('F_B', String(55)),
    Column('Taxes', String(55)),
    Column('Other', String(55)),
    Column('Month_To_Date_Room_Nights', String(55)),
    Column('Month_To_Date_Room', String(55)),
    Column('Month_To_Date_F_B', String(55)),
    Column('Month_To_Date_Taxes', String(55)),
    Column('Month_To_Date_Others', String(55)),
    Column('Year_To_Date_Room_Nights', String(55)),
    Column('Year_To_Date__Room', String(55)),
    Column('Year_To_Date_F_B', String(55)),
    Column('Year_To_Date_Taxes', String(55)),
    Column('Year_To_Date_Other', String(55)),
    Column('Room_Nights_Total', String(55)),
    Column('Room_Total', String(55)),
    Column('F_B_Total', String(55)),
    Column('Taxes_Total', String(55)),
    Column('Other_Total', String(55)),
    Column('Month_To_Date_Room_Nights_Total', String(55)),
    Column('Month_To_Date_Room_Total', String(55)),
    Column('Month_To_Date_F_B_total', String(55)),
    Column('Month_To_Date_Taxes_Total', String(55)),
    Column('Month_To_Date_Total', String(55)),
    Column('Year_To_Date_Room_Nights_Total', String(55)),
    Column('Year_To_Date_Room_Total', String(55)),
    Column('Year_To_Date_F_B_Total', String(55)),
    Column('Year_To_Date_Taxes_Total', String(55)),
    Column('Year_To_Date_Total', String(55)),
)

synxis_cloud_monthly_summary_model = Table(
    'synxis_cloud_monthly_summary', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('BUSINESS_DT', String(55)),
    Column('OCCUPIED_ROOM_QTY', String(55)),
    Column('RENTABLE_ROOM_QTY', String(55)),
    Column('OCCUPANCY_PERCENT', String(55)),
    Column('ADR_WITH_COMPS', String(55)),
    Column('TOTAL_FOOD_AND_BEV_REV', String(55)),
    Column('TOTAL_ROOM_REV1', String(55)),
    Column('TOTAL_TAX_REV', String(55)),
    Column('TOTAL_OTH_REV', String(55)),
    Column('TOTAL_REV', String(55)),
    Column('Date', String(55)),
    Column('OCCUPIED_ROOM_QTY_Total', String(55)),
    Column('RENTABLE_ROOM_QTY_Total', String(55)),
    Column('Occupancy_Percent_Total', String(55)),
    Column('ADR_Total', String(55)),
    Column('FoodandBeverage', String(55)),
    Column('RoomCharges', String(55)),
    Column('Taxes', String(55)),
    Column('Others', String(55)),
    Column('Total', String(55)),
)

marriott_reservation_model = Table(
    'marriott_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('StayYearCalendar', String(55)),
    Column('StayYYYYMM', String(55)),
    Column('CustomWDWE', String(55)),
    Column('StayDOWText', String(55)),
    Column('StayDate', String(55)),
    Column('ArrivalIndicator', String(55)),
    Column('BookingDate', String(55)),
    Column('AVPName', String(55)),
    Column('BrandName', String(55)),
    Column('HtlComparableText', String(55)),
    Column('PropertyCountryRegion', String(55)),
    Column('HotelTypeName', String(55)),
    Column('ManagementType', String(55)),
    Column('MARSHACode', String(55)),
    Column('PublicClusterName', String(55)),
    Column('GlobalRegionName', String(55)),
    Column('GlobalDivision', String(55)),
    Column('MarketCategory', String(55)),
    Column('MarketSegmentNameforReport', String(55)),
    Column('MarketPrfxNameforReport', String(55)),
    Column('RateProgramCode', String(55)),
    Column('RateProgramName', String(55)),
    Column('RateProgramTier', String(55)),
    Column('RateCategoryCode', String(55)),
    Column('MarketCode', String(55)),
    Column('OpportunityNum', String(55)),
    Column('QuoteNum', String(55)),
    Column('LengthofAccomLOA', String(55)),
    Column('LOATierID', String(55)),
    Column('NightsOut', String(55)),
    Column('NightsOutTier', String(55)),
    Column('ChannelAggregateName', String(55)),
    Column('ChannelDetailName', String(55)),
    Column('ChannelTypeName', String(55)),
    Column('ChannelSiteName', String(55)),
    Column('ChannelPartnerName', String(55)),
    Column('BookingSourceType', String(55)),
    Column('BookingOffice', String(55)),
    Column('IntermediaryTypeCode', String(55)),
    Column('Intermediary', String(55)),
    Column('RoomCategoryCode', String(55)),
    Column('RoomPoolCode', String(55)),
    Column('MARSHARateNet', String(55)),
    Column('RewardsLevelText', String(55)),
    Column('RoomNights', String(55)),
    Column('ADRNet', String(55)),
    Column('RevenueNet', String(55)),
    Column('AverageRoomNights', String(55)),
    Column('AverageRevenue', String(55)),
)

marriott_forecast_model = Table(
    'marriott_forecast', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('ArrivalDate', String(55)),
    Column('ArrivalDay', String(55)),
    Column('WEindicator', String(55)),
    Column('Capacity', String(55)),
    Column('DaysOut', String(55)),
    Column('SysRemDem', String(55)),
    Column('RemDemSTLY', String(55)),
    Column('AppliedRemDem', String(55)),
    Column('UserOverride', String(55)),
    Column('Event', String(55)),
    Column('OYv2TotalHotelOccupancy', String(55)),
    Column('TotalAvailableTransientSupply', String(55)),
    Column('TotalTransientBooked', String(55)),
    Column('TotalTransientBookedSTLY', String(55)),
    Column('AdditionalDemand', String(55)),
    Column('AdditionalDemandSTLY', String(55)),
    Column('TotalTransientDemand', String(55)),
    Column('TotalTransientDemandSTLY', String(55)),
    Column('AllotmentForecast', String(55)),
    Column('AllotmentRoomsSold', String(55)),
    Column('OutofOrder', String(55)),
    Column('GroupRoomBlockAuthorized', String(55)),
    Column('GroupBooked', String(55)),
    Column('OYv2GroupProj', String(55)),
    Column('ContractRoomBlockAuthorized', String(55)),
    Column('ContractBooked', String(55)),
    Column('OYv2ContractProj', String(55)),
    Column('ComplimentaryBookedTY', String(55)),
    Column('RemDemPremiumRetailTY', String(55)),
    Column('RemDemPremiumRetailTYPer', String(55)),
    Column('PremiumRetailTY', String(55)),
    Column('RemDemPremiumRetailSTLY', String(55)),
    Column('RemDemPremiumRetailSTLYPer', String(55)),
    Column('PremiumRetailSTLY', String(55)),
    Column('RemDemStandardRetailTY', String(55)),
    Column('RemDemStandardRetailTYPer', String(55)),
    Column('StandardRetailTY', String(55)),
    Column('RemDemStandardRetailSTLY', String(55)),
    Column('RemDemStandardRetailSTLYPer', String(55)),
    Column('StandardRetailSTLY', String(55)),
    Column('RemDemSpecialCorporateLRATY', String(55)),
    Column('RemDemSpecialCorporateLRATYPer', String(55)),
    Column('SpecialCorporateLRATY', String(55)),
    Column('RemDemSpecialCorporateLRASTLY', String(55)),
    Column('RemDemSpecialCorporateLRASTLYPer', String(55)),
    Column('SpecialCorporateLRASTLY', String(55)),
    Column('RemDemRewardRedemptionTY', String(55)),
    Column('RemDemRewardRedemptionTYPer', String(55)),
    Column('RewardRedemptionTY', String(55)),
    Column('RemDemRewardRedemptionSTLY', String(55)),
    Column('RemDemRewardRedemptionSTLYPer', String(55)),
    Column('RewardRedemptionSTLY', String(55)),
    Column('RemDemPolicyDrivenTY', String(55)),
    Column('RemDemPolicyDrivenTYPer', String(55)),
    Column('PolicyDrivenTY', String(55)),
    Column('RemDemPolicyDrivenSTLY', String(55)),
    Column('RemDemPolicyDrivenSTLYPer', String(55)),
    Column('PolicyDrivenSTLY', String(55)),
    Column('RemDemGovtMilitaryTY', String(55)),
    Column('RemDemGovtMilitaryTYPer', String(55)),
    Column('GovtMilitaryTY', String(55)),
    Column('RemDemGovtMilitarySTLY', String(55)),
    Column('RemDemGovtMilitarySTLYPer', String(55)),
    Column('GovtMilitarySTLY', String(55)),
    Column('RemDemRetailTiedDiscountTY', String(55)),
    Column('RemDemRetailTiedDiscountTYPer', String(55)),
    Column('RetailTiedDiscountTY', String(55)),
    Column('RemDemRetailTiedDiscountSTLY', String(55)),
    Column('RemDemRetailTiedDiscountSTLYPer', String(55)),
    Column('RetailTiedDiscountSTLY', String(55)),
    Column('RemDemFixedDiscountTY', String(55)),
    Column('RemDemFixedDiscountTYPer', String(55)),
    Column('FixedDiscountTY', String(55)),
    Column('RemDemFixedDiscountSTLY', String(55)),
    Column('RemDemFixedDiscountSTLYPer', String(55)),
    Column('FixedDiscountSTLY', String(55)),
    Column('RoomCollection1HurdleRevenue', String(55)),
    Column('RoomCollection1TransientOTBTY', String(55)),
    Column('RoomCollection1TransientOTBSTLY', String(55)),
    Column('RoomCollection1RemDemTY', String(55)),
    Column('RoomCollection1RemDemTYPer', String(55)),
    Column('RoomCollection1RemDemSTLY', String(55)),
    Column('RoomCollection1RemDemSTLYPer', String(55)),
    Column('RoomCollection2HurdleRevenue', String(55)),
    Column('RoomCollection2TransientOTBTY', String(55)),
    Column('RoomCollection2TransientOTBSTLY', String(55)),
    Column('RoomCollection2RemDemTY', String(55)),
    Column('RoomCollection2RemDemTYPer', String(55)),
    Column('RoomCollection2RemDemSTLY', String(55)),
    Column('RoomCollection2RemDemSTLYPer', String(55)),
)

hotelkey_occ_model = Table(
    'hotelkey_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('Date', String(55)),
    Column('Property', String(55)),
    Column('PFRZ', String(55)),
    Column('FRZ', String(55)),
    Column('TOD', String(55)),
    Column('DOW', String(55)),
    Column('GTD', String(55)),
    Column('LOS', String(55)),
    Column('CXL', String(55)),
    Column('OO', String(55)),
    Column('Hold', String(55)),
    Column('Yieldable', String(55)),
    Column('Sold', String(55)),
    Column('BLK', String(55)),
    Column('SD', String(55)),
    Column('OccOTB', String(55)),
    Column('OccPYClose', String(55)),
    Column('OccPYVar', String(55)),
    Column('ADROTB', String(55)),
    Column('ADRPYClose', String(55)),
    Column('ADRPYVar', String(55)),
    Column('DiscPer', String(55)),
    Column('Price1', String(55)),
    Column('LT1', String(55)),
    Column('Per1', String(55)),
    Column('RM1', String(55)),
    Column('Price2', String(55)),
    Column('LT2', String(55)),
    Column('Per2', String(55)),
    Column('RM2', String(55)),
    Column('Price3', String(55)),
    Column('LT3', String(55)),
    Column('Per3', String(55)),
    Column('RM3', String(55)),
    Column('Price4', String(55)),
    Column('LT4', String(55)),
    Column('Per4', String(55)),
    Column('RM4', String(55)),
)

hotelkey_res_model = Table(
    'hotelkey_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('Property', String(55)),
    Column('Status', String(55)),
    Column('Channel', String(55)),
    Column('Res', String(55)),
    Column('GuestName', String(55)),
    Column('ArrivalDate', String(55)),
    Column('DepartDate', String(55)),
    Column('Nts', String(55)),
    Column('Adl', String(55)),
    Column('MarketSegment', String(55)),
    Column('Group', String(55)),
    Column('RateCode', String(55)),
    Column('Product', String(55)),
    Column('AssignedProduct', String(55)),
    Column('Rate', String(55)),
    Column('TaxInc', String(55)),
    Column('ProjectedRevenue', String(55)),
    Column('TotalWithoutTax', String(55)),
    Column('PayMth', String(55)),
    Column('PaymentsTaken', String(55)),
    Column('DepositsScheduled', String(55)),
    Column('BalanceDue', String(55)),
    Column('CreationDate', String(55)),
    Column('CreationUser', String(55)),
    Column('CP', String(55)),
    Column('CPName', String(55)),
    Column('Blank', String(55)),
)

visual_matrix_front_office_arrival_model = Table(
    'visual_matrix_front_office_arrival', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('GuestName', String(55)),
    Column('Status', String(55)),
    Column('Arrive', String(55)),
    Column('Departs', String(55)),
    Column('A', String(55)),
    Column('C', String(55)),
    Column('Type', String(55)),
    Column('Rate', String(55)),
    Column('PKG', String(55)),
    Column('MOP', String(55)),
    Column('ADV_DEP', String(55)),
    Column('Share', String(55)),
    Column('Room', String(55)),
)

visual_matrix_occupancy_model = Table(
    'visual_matrix_occupancy', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(55)),
    Column('pullDateId', BIGINT),
    Column('Date', String(55)),
    Column('Day', String(55)),
    Column('Maint', String(55)),
    Column('GuestArrivals_Non_GTD', String(55)),
    Column('GuestArrivals_GTD', String(55)),
    Column('GroupArrivals_Non_GTD', String(55)),
    Column('GroupArrivals_GTD', String(55)),
    Column('GroupAlloc', String(55)),
    Column('ARV', String(55)),
    Column('Dep', String(55)),
    Column('StayOvers', String(55)),
    Column('AvailRms', String(55)),
    Column('OccRms', String(55)),
    Column('OccPer', String(55)),
    Column('RmRev', String(55)),
    Column('ADR', String(55)),
    Column('RevPar', String(55)),
    Column('ActualRoomsLY', String(55)),
    Column('OccPerVariance', String(55)),
)
# meta.create_all(engine)
