from sqlalchemy import *

meta = MetaData()

choice_res_model = Table(
    'choice_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Account', String(20)),
    Column('GuestName', Text()),
    Column('Arrive', String(10)),
    Column('Depart', String(10)),
    Column('Nights', String(20)),
    Column('Status', String(20)),
    Column('Rate', String(20)),
    Column('RateCode', String(20)),
    Column('Type', String(20)),
    Column('Room', String(20)),
    Column('Source', String(20)),
    Column('CRSConfNo', String(20)),
    Column('GTD', String(20)),
    Column('ReserveDate', String(20)),
    Column('ReserveTime', String(20)),
    Column('User', String(20)),
    Column('SharedAccount', String(20)),
    Column('TrackCode', String(20)),
    Column('Package', String(20)),
    Column('CancellationDate', String(10)),
    Column('CancellationTime', String(8)),
    Column('CXLUserID', String(255)),
)

choice_occ_model = Table(
    'choice_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('IDS_DATE', String(20)),
    Column('Day', String(20)),
    Column('Rooms', String(10)),
    Column('OOO', String(10)),
    Column('StayOver', String(20)),
    Column('Arrivals', String(20)),
    Column('DueOut', String(20)),
    Column('Available', String(20)),
    Column('GroupBlock', String(20)),
    Column('GroupPickedUp', String(20)),
    Column('TransNGTD', String(20)),
    Column('TransGTD', String(20)),
    Column('Occupied', String(20)),
    Column('OccPercent', String(20)),
    Column('RoomRev', String(20)),
    Column('RevPAR', String(20)),
    Column('ADR', String(20)),
    Column('Ppl', String(20))
)

auto_clerk_res_model = Table(
    'auto_clerk_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('DateTime', String(20)),
    Column('Status', String(20)),
    Column('MyhmsConf', String(20)),
    Column('CRSConf', String(20)),
    Column('roomnumber', String(20)),
    Column('roomtype', String(20)),
    Column('rateplan', String(20)),
    Column('rate', String(20)),
    Column('Paytype', String(20)),
    Column('arrivaldate', String(20)),
    Column('departuredate', String(20)),
    Column('nights', String(20)),
    Column('guestlastname', String(20)),
    Column('guestfirstname', String(20)),
    Column('address1', Text),
    Column('address2', Text),
    Column('city', String(20)),
    Column('state', String(20)),
    Column('zip', String(20)),
    Column('country', String(20)),
    Column('phone', String(20)),
    Column('email', String(20)),
    Column('TotalRevenueforstay', String(20)),
    Column('RoomRevenueforstay', String(20)),
    Column('source', String(20)),
    Column('market', String(20)),
    Column('channel', String(20)),
    Column('companyName', String(20)),
    Column('drivingLicence', String(20))
)

auto_clerk_occ_model = Table(
    'auto_clerk_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('Date', String(20)),
    Column('Rooms', String(20)),
    Column('Arrivals', String(20)),
    Column('StayOver', String(20)),
    Column('DepartToday', String(20)),
    Column('OccupRooms', String(20)),
    Column('UnusedGroupBlocks', String(20)),
    Column('Occup', String(20)),
    Column('A', String(20)),
    Column('C', String(20)),
    Column('I', String(20)),
    Column('RoomRevenue', String(20)),
    Column('ADR', String(20)),
    Column('REVPAR', String(20)),
    Column('OOORooms', String(20)),
    Column('UnusedAllotment', String(20)),
    Column('AvailRooms', String(20))
)

ihg_res_model = Table(
    'ihg_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('ConfirmationNumber', String(20)),
    Column('PriorityClubMember', String(20)),
    Column('GuestName', String(20)),
    Column('ArrivalDate', String(20)),
    Column('TransactionTime(GMT)', String(20)),
    Column('RateCode', String(20)),
    Column('RateCategory', String(20)),
    Column('Guaranteed', String(20)),
    Column('RoomType', String(20)),
    Column('ArrivalRoomRate', String(20)),
    Column('NumberofGuests', String(20)),
    Column('NumberofNights', String(20)),
    Column('NumberofRooms', String(20)),
    Column('PropertyName', String(20)),
    Column('ATLTM', String(20))
)

ihg_occ_model = Table(
    'ihg_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('BlackoutDates', String(20)),
    Column('blank', String(20)),
    Column('ClosedtoArrival', String(20)),
    Column('Date', String(20)),
    Column('DayofWeek', String(20)),
    Column('MaximumLOS', String(20)),
    Column('MinimumLOS', String(20)),
    Column('ReservationGuaranteeRequired', String(20)),
    Column('24Hourhold', String(20)),
    Column('AverageLeadTime', String(20)),
    Column('AverageLOS', String(20)),
    Column('CancelDue', String(20)),
    Column('CancelorNoShow', String(20)),
    Column('DepositDue', String(20)),
    Column('Deposit', String(20)),
    Column('Groupremaining', String(20)),
    Column('RoomslefttoSell', String(20)),
    Column('SpecialEventSpecialRequirement', String(20)),
    Column('Paceasofdate', String(20)),
    Column('AC', String(20)),
    Column('ActualroomssoldLY', String(20)),
    Column('ADR', String(20)),
    Column('BFR', String(20)),
    Column('Groupcommitted', String(20)),
    Column('Groupcontracted', String(20)),
    Column('GroupPickupasofdate', String(20)),
    Column('Grouppickup', String(20)),
    Column('Occ', String(20)),
    Column('OVB', String(20)),
    Column('Paceasofdate1', String(20)),
    Column('Paceasofdate2', String(20)),
    Column('Pickupasofdate', String(20)),
    Column('Pickupasofdate1', String(20)),
    Column('Roomssold', String(20)),
    Column('TotalRoomsCommitted', String(20)),
)

opera_occ_model = Table(
    'opera_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('REVENUE', String(55)),
    Column('NO_ROOMS', String(55)),
    Column('IND_DEDUCT_ROOMS', String(55)),
    Column('IND_NON_DEDUCT_ROOMS', String(55)),
    Column('GRP_DEDUCT_ROOMS', String(55)),
    Column('GRP_NON_DEDUCT_ROOMS', String(55)),
    Column('NO_PERSONS', String(55)),
    Column('ARRIVAL_ROOMS', String(55)),
    Column('DEPARTURE_ROOMS', String(55)),
    Column('COMPLIMENTARY_ROOMS', String(55)),
    Column('HOUSE_USE_ROOMS', String(55)),
    Column('DAY_USE_ROOMS', String(55)),
    Column('NO_SHOW_ROOMS', String(55)),
    Column('INVENTORY_ROOMS', String(55)),
    Column('CONSIDERED_DATE', String(55)),
    Column('CHAR_CONSIDERED_DATE', String(55)),
    Column('IND_DEDUCT_REVENUE', String(55)),
    Column('IND_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_NON_DEDUCT_REVENUE', String(55)),
    Column('GRP_DEDUCT_REVENUE', String(55)),
    Column('OWNER_ROOMS', String(55)),
    Column('FF_ROOMS', String(55)),
    Column('CF_OOO_ROOMS', String(55)),
    Column('CF_CALC_OCC_ROOMS', String(55)),
    Column('CF_CALC_INV_ROOMS', String(55)),
    Column('CF_AVERAGE_ROOM_RATE', String(55)),
    Column('CF_OCCUPANCY', String(55)),
    Column('CF_IND_DED_REV', String(55)),
    Column('CF_IND_NON_DED_REV', String(55)),
    Column('CF_BLK_DED_REV', String(55)),
    Column('CF_BLK_NON_DED_REV', String(55))
)

opera_res_model = Table(
    'opera_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(20)),
    Column('RESV_NAME_ID', String(55)),
    Column('GUARANTEE_CODE', String(55)),
    Column('RESV_STATUS', String(55)),
    Column('ROOM', String(55)),
    Column('FULL_NAME', String(55)),
    Column('DEPARTURE', String(55)),
    Column('PERSONS', String(55)),
    Column('GROUP_NAME', String(55)),
    Column('NO_OF_ROOMS', String(55)),
    Column('ROOM_CATEGORY_LABEL', String(55)),
    Column('RATE_CODE', String(55)),
    Column('INSERT_USER', String(55)),
    Column('INSERT_DATE', String(55)),
    Column('GUARANTEE_CODE_DESC', String(55)),
    Column('COMPANY_NAME', String(55)),
    Column('TRAVEL_AGENT_NAME', String(55)),
    Column('ARRIVAL', String(55)),
    Column('NIGHTS', String(55)),
    Column('COMP_HOUSE_YN', String(55)),
    Column('SHARE_AMOUNT', String(55)),
    Column('C_T_S_NAME', String(55)),
    Column('SHORT_RESV_STATUS', String(55)),
    Column('SHARE_AMOUNT_PER_STAY', String(55)),
)

# meta.create_all(engine)
