from sqlalchemy import *

meta = MetaData()

choice_res_model = Table(
    'choice_res', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Account', String(255)),
    Column('GuestName', Text()),
    Column('Arrive', String(255)),
    Column('Depart', String(255)),
    Column('Nights', String(255)),
    Column('Status', String(255)),
    Column('Rate', String(255)),
    Column('RateCode', String(255)),
    Column('Type', String(255)),
    Column('Room', String(255)),
    Column('Source', String(255)),
    Column('CRSConfNo', String(255)),
    Column('GTD', String(255)),
    Column('ReserveDate', String(255)),
    Column('ReserveTime', String(255)),
    Column('User', String(255)),
    Column('SharedAccount', String(255)),
    Column('TrackCode', String(255)),
    Column('Package', String(255)),
    Column('CancellationDate', String(255)),
    Column('CancellationTime', String(255)),
    Column('CXLUserID', String(255)),
)

choice_occ_model = Table(
    'choice_occ', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('IDS_DATE', String(255)),
    Column('Day', String(255)),
    Column('Rooms', String(255)),
    Column('OOO', String(255)),
    Column('StayOver', String(255)),
    Column('Arrivals', String(255)),
    Column('DueOut', String(255)),
    Column('Available', String(255)),
    Column('GroupBlock', String(255)),
    Column('GroupPickedUp', String(255)),
    Column('TransNGTD', String(255)),
    Column('TransGTD', String(255)),
    Column('Occupied', String(255)),
    Column('OccPercent', String(255)),
    Column('RoomRev', String(255)),
    Column('RevPAR', String(255)),
    Column('ADR', String(255)),
    Column('Ppl', String(255))
)

choice_busi_model = Table(
    'choice_busi_on_books', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('Date', String(255)),
    Column('TransientRooms', String(255)),
    Column('TransientPPL', String(10)),
    Column('GroupRooms', String(10)),
    Column('GroupPPL', String(255)),
    Column('DefiniteNotPickup', String(255)),
    Column('TentativeNotPickup', String(255)),
    Column('TotalOccupiedRooms', String(255)),
    Column('TotalPPL', String(255)),
    Column('Occ', String(255)),
    Column('COMPS', String(255)),
    Column('RoomRev', String(255)),
    Column('RevPar', String(255)),
    Column('ADR', String(255)),
)

choice_cancellation_model = Table(
    'choice_cancellation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('CancellationReason', String(255)),
    Column('CxlDate', String(255)),
    Column('Resv', String(255)),
    Column('RoomNights', String(255)),
    Column('RoomRev', String(255)),
)

choice_revenue_model = Table(
    'choice_revenue', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('IDS_RATE_CODE', String(255)),
    Column('RoomNights', String(255)),
    Column('RoomNightsPer', String(255)),
    Column('RoomRevenue', String(255)),
    Column('RoomRevenuePer', String(255)),
    Column('DailyAVG', String(255)),
    Column('PTDRoomNights', String(255)),
    Column('PTDRoomNightsPer', String(255)),
    Column('PTDRoomRevenue', String(255)),
    Column('PTDRoomRevenuePer', String(255)),
    Column('PTD_AVG', String(255)),
    Column('YTDRoomNights', String(255)),
    Column('YTDRoomNightsPer', String(255)),
    Column('YTDRoomRevenue', String(255)),
    Column('YTDRoomRevenuePer', String(255)),
    Column('YTD_AVG', String(255)),
)

choice_revenue_detail_model = Table(
    'choice_revenue_detail', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('IDS_DATE_DAY', String(255)),
    Column('RateCode', String(255)),
    Column('RoomNights', String(255)),
    Column('RoomNightsPer', String(255)),
    Column('RoomRevenue', String(255)),
    Column('RoomRevenuePer', String(255)),
    Column('DailyAVG', String(255)),
)

choice_group_pickup_detail_model = Table(
    'choice_group_pickup_detail', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('GroupName', String(255)),
    Column('GroupStatus', String(255)),
    Column('RollingCutOffDays', String(255)),
    Column('FixedCutOffDate', String(255)),
    Column('SalesManager', String(255)),
    Column('RoomType', String(255)),
    Column('BlockDate', String(255)),
    Column('OriginalBlock', String(255)),
    Column('CurrentBlock', String(255)),
    Column('GuaranteedArrivalsPickedUp', String(255)),
    Column('NonGuaranteedArrivalsPickedUp', String(255)),
    Column('TotalPickedUp', String(255)),
    Column('RoomsNotPickedUp', String(255)),
    Column('Revenue', String(255)),
    Column('ADR', String(255)),
)

choice_cancellation_list_model = Table(
    'choice_cancellation_list', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Account', String(255)),
    Column('Guest_Name', String(255)),
    Column('Arrival_Group', String(255)),
    Column('Nights', String(255)),
    Column('Rate_Plan', String(255)),
    Column('GTD', String(255)),
    Column('Source', String(255)),
    Column('Rm_Type', String(255)),
    Column('Cxl_Code', String(255)),
    Column('Cxl_Date', String(255)),
    Column('Cxl_Clk', String(255)),
)

choice_noshow_model = Table(
    'choice_noshow', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True), 
    Column('account', String(255)),
    Column('guestName', String(255)),
    Column('arrival', String(255)),
    Column('departure', String(255)),
    Column('source', String(255)),
    Column('GTD', String(255)),
    Column('ratePlan', String(255)),
    Column('rate', String(255)),
    Column('balance', String(255)),
    Column('payment', String(255)),
    Column('authStatus', String(255)),
)

auto_clerk_res_model = Table(
    'auto_clerk_res', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('DateTime', String(255)),
    Column('Status', String(255)),
    Column('MyhmsConf', String(255)),
    Column('CRSConf', String(255)),
    Column('roomnumber', String(255)),
    Column('roomtype', String(255)),
    Column('rateplan', String(255)),
    Column('rate', String(255)),
    Column('Paytype', String(255)),
    Column('arrivaldate', String(255)),
    Column('departuredate', String(255)),
    Column('nights', String(255)),
    Column('guestlastname', String(255)),
    Column('guestfirstname', String(255)),
    Column('address1', Text),
    Column('address2', Text),
    Column('city', String(255)),
    Column('state', String(255)),
    Column('zip', String(255)),
    Column('country', String(255)),
    Column('phone', String(255)),
    Column('email', String(255)),
    Column('TotalRevenueforstay', String(255)),
    Column('RoomRevenueforstay', String(255)),
    Column('source', String(255)),
    Column('market', String(255)),
    Column('channel', String(255)),
    Column('companyName', String(255)),
    Column('drivingLicence', String(255))
)

auto_clerk_occ_model = Table(
    'auto_clerk_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('Date', String(255)),
    Column('Rooms', String(255)),
    Column('Arrivals', String(255)),
    Column('StayOver', String(255)),
    Column('DepartToday', String(255)),
    Column('OccupRooms', String(255)),
    Column('UnusedGroupBlocks', String(255)),
    Column('Occup', String(255)),
    Column('A', String(255)),
    Column('C', String(255)),
    Column('I', String(255)),
    Column('RoomRevenue', String(255)),
    Column('ADR', String(255)),
    Column('REVPAR', String(255)),
    Column('OOORooms', String(255)),
    Column('UnusedAllotment', String(255)),
    Column('AvailRooms', String(255))
)

auto_clerk_group_block_summary_model = Table(
    'auto_clerk_group_block_summary', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('GroupBookingName', String(255)),
    Column('Confirmation', String(255)),
    Column('Arrive', String(255)),
    Column('Depart', String(255)),
    Column('Block', String(255)),
    Column('P_U', String(255)),
    Column('Diff', String(255)),
    Column('BlockedRevenue', String(255)),
    Column('PickedUpRevenue', String(255)),
    Column('CutoffDate', String(255)),
)

ihg_res_model = Table(
    'ihg_res', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('ArrivalDate', String(255)),
    Column('ConfirmationNumber', String(255)),
    Column('Guaranteed', String(255)),
    Column('GuestName', String(255)),
    Column('PriorityClubMember', String(255)),
    Column('PropertyName', String(255)),
    Column('RateCategory', String(255)),
    Column('RateCode', String(255)),
    Column('RoomType', String(255)),
    Column('TransactionTime(GMT)', String(255)),
    Column('ArrivalRoomRate', String(255)),
    Column('NumberofGuests', String(255)),
    Column('NumberofNights', String(255)),
    Column('NumberofRooms', String(255)),
    Column('HotelCode', String(255))
)

ihg_occ_model = Table(
    'ihg_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('BlackoutDates', String(255)),
    Column('blank', String(255)),
    Column('ClosedtoArrival', String(255)),
    Column('Date', String(255)),
    Column('DayofWeek', String(255)),
    Column('MaximumLOS', String(255)),
    Column('MinimumLOS', String(255)),
    Column('ReservationGuaranteeRequired', String(255)),
    Column('24Hourhold', String(255)),
    Column('AverageLeadTime', String(255)),
    Column('AverageLOS', String(255)),
    Column('CancelDue', String(255)),
    Column('CancelorNoShow', String(255)),
    Column('DepositDue', String(255)),
    Column('Deposit', String(255)),
    Column('Groupremaining', String(255)),
    Column('RoomslefttoSell', String(255)),
    Column('SpecialEventSpecialRequirement', String(255)),
    Column('Paceasofdate', String(255)),
    Column('AC', String(255)),
    Column('ActualroomssoldLY', String(255)),
    Column('ADR', String(255)),
    Column('BFR', String(255)),
    Column('Groupcommitted', String(255)),
    Column('Groupcontracted', String(255)),
    Column('GroupPickupasofdate', String(255)),
    Column('Grouppickup', String(255)),
    Column('Occ', String(255)),
    Column('OVB', String(255)),
    Column('Paceasofdate1', String(255)),
    Column('Paceasofdate2', String(255)),
    Column('Pickupasofdate', String(255)),
    Column('Pickupasofdate1', String(255)),
    Column('Roomssold', String(255)),
    Column('TotalRoomsCommitted', String(255)),
)

opera_occ_model = Table(
    'opera_occ', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('REVENUE', String(255)),
    Column('NO_ROOMS', String(255)),
    Column('IND_DEDUCT_ROOMS', String(255)),
    Column('IND_NON_DEDUCT_ROOMS', String(255)),
    Column('GRP_DEDUCT_ROOMS', String(255)),
    Column('GRP_NON_DEDUCT_ROOMS', String(255)),
    Column('NO_PERSONS', String(255)),
    Column('ARRIVAL_ROOMS', String(255)),
    Column('DEPARTURE_ROOMS', String(255)),
    Column('COMPLIMENTARY_ROOMS', String(255)),
    Column('HOUSE_USE_ROOMS', String(255)),
    Column('DAY_USE_ROOMS', String(255)),
    Column('NO_SHOW_ROOMS', String(255)),
    Column('INVENTORY_ROOMS', String(255)),
    Column('CONSIDERED_DATE', String(255)),
    Column('CHAR_CONSIDERED_DATE', String(255)),
    Column('IND_DEDUCT_REVENUE', String(255)),
    Column('IND_NON_DEDUCT_REVENUE', String(255)),
    Column('GRP_NON_DEDUCT_REVENUE', String(255)),
    Column('GRP_DEDUCT_REVENUE', String(255)),
    Column('OWNER_ROOMS', String(255)),
    Column('FF_ROOMS', String(255)),
    Column('CF_OOO_ROOMS', String(255)),
    Column('CF_CALC_OCC_ROOMS', String(255)),
    Column('CF_CALC_INV_ROOMS', String(255)),
    Column('CF_AVERAGE_ROOM_RATE', String(255)),
    Column('CF_OCCUPANCY', String(255)),
    Column('CF_IND_DED_REV', String(255)),
    Column('CF_IND_NON_DED_REV', String(255)),
    Column('CF_BLK_DED_REV', String(255)),
    Column('CF_BLK_NON_DED_REV', String(255))
)

opera_res_model = Table(
    'opera_res', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('RESV_NAME_ID', String(255)),
    Column('GUARANTEE_CODE', String(255)),
    Column('RESV_STATUS', String(255)),
    Column('ROOM', String(255)),
    Column('FULL_NAME', String(255)),
    Column('DEPARTURE', String(255)),
    Column('PERSONS', String(255)),
    Column('GROUP_NAME', String(255)),
    Column('NO_OF_ROOMS', String(255)),
    Column('ROOM_CATEGORY_LABEL', String(255)),
    Column('RATE_CODE', String(255)),
    Column('INSERT_USER', String(255)),
    Column('INSERT_DATE', String(255)),
    Column('GUARANTEE_CODE_DESC', String(255)),
    Column('COMPANY_NAME', String(255)),
    Column('TRAVEL_AGENT_NAME', String(255)),
    Column('ARRIVAL', String(255)),
    Column('NIGHTS', String(255)),
    Column('COMP_HOUSE_YN', String(255)),
    Column('SHARE_AMOUNT', String(255)),
    Column('C_T_S_NAME', String(255)),
    Column('SHORT_RESV_STATUS', String(255)),
    Column('SHARE_AMOUNT_PER_STAY', String(255)),
)

opera_rbrc_model = Table(
    'opera_rbrc', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('RESORT', String(255)),
    Column('BUSINESS_DATE', String(255)),
    Column('CHAR_BUSINESS_DATE', String(255)),
    Column('MASTER_VALUE', String(255)),
    Column('CF_MASTER_SEQ', String(255)),
    Column('GROUP_NAME', String(255)),
    Column('ARR_TODAY', String(255)),
    Column('NO_DEFINITE_ROOMS', String(255)),
    Column('IN_GUEST', String(255)),
    Column('OCC_SINGLE', String(255)),
    Column('DOUBLE_OCC', String(255)),
    Column('REVENUE', String(255)),
    Column('FB_REV', String(255)),
    Column('OTHER_REV', String(255)),
    Column('TOTAL_REVENUE', String(255)),
    Column('RESORT_ROOM', String(255)),
    Column('PER_OCC', String(255)),
    Column('GET_ARR', String(255)),
    Column('MULTI_OCC_PER', String(255)),
)

opera_arrival_model = Table(
    'opera_arrival', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('REDEEM_FLAG_YN', String(255)),
    Column('MOBILE_REGSITERED_YN', String(255)),
    Column('TOTAL_STAYS_ACROSS_CHAIN', String(255)),
    Column('TOTAL_NIGHTS_ACROSS_CHAIN', String(255)),
    Column('EXTERNAL_REFERENCE', String(255)),
    Column('UPDATE_DATE', String(255)),
    Column('UPDATE_USER', String(255)),
    Column('DISP_ROOM_NO', String(255)),
    Column('RESV_COLOR', String(255)),
    Column('ROWNUM', String(255)),
    Column('IS_SHARED_YN', String(255)),
    Column('TRUNC_BEGIN', String(255)),
    Column('TRUNC_END', String(255)),
    Column('CONFIRMATION_NO', String(255)),
    Column('ARRIVAL', String(255)),
    Column('PRODUCTS', String(255)),
    Column('SHORT_RESV_STATUS', String(255)),
    Column('RESORT', String(255)),
    Column('FULL_NAME_NO_SHR_IND', String(255)),
    Column('ARRIVAL_TIME1', String(255)),
    Column('ARRIVAL_TRANSPORT_TYPE', String(255)),
    Column('FULL_NAME', String(255)),
    Column('NO_OF_ROOMS', String(255)),
    Column('ROOM_CATEGORY_LABEL', String(255)),
    Column('ARRIVAL_TIME', String(255)),
    Column('DEPARTURE_TIME', String(255)),
    Column('MARKET_CODE', String(255)),
    Column('RATE_CODE', String(255)),
    Column('DEPARTURE', String(255)),
    Column('VIP', String(255)),
    Column('GUARANTEE_CODE', String(255)),
    Column('BILL_TO_ADDRESS', String(255)),
    Column('PREFERRED_ROOM_TYPE', String(255)),
    Column('BEGIN_DATE', String(255)),
    Column('GROUP_ID', String(255)),
    Column('BLOCK_CODE', String(255)),
    Column('ORIGIN_OF_BOOKING', String(255)),
    Column('EFFECTIVE_RATE_AMOUNT', String(255)),
    Column('SPECIAL_REQUESTS', String(255)),
    Column('EXP_DATE', String(255)),
    Column('PAYMENT_METHOD', String(255)),
    Column('ADULTS', String(255)),
    Column('CHILDREN', String(255)),
    Column('PERSONS', String(255)),
    Column('DEPOSIT_PAID', String(255)),
    Column('ARRIVAL_CARRIER_CODE', String(255)),
    Column('COMPANY_NAME', String(255)),
    Column('CURRENCY_CODE', String(255)),
    Column('ROOM_NO', String(255)),
    Column('SHARE_AMOUNT', String(255)),
    Column('CREDIT_CARD_NUMBER', String(255)),
    Column('PHYSICAL_QUANTITY', String(255)),
    Column('RESV_NAME_ID', String(255)),
    Column('GUEST_NAME_ID', String(255)),
    Column('PREFERENCES', String(255)),
    Column('LAST_ROOM', String(255)),
    Column('SHARE_NAMES', String(255)),
    Column('ACCOMPANYING_YN', String(255)),
    Column('COMP_HOUSE', String(255)),
    Column('ACCOMPANYING_NAMES', String(255)),
    Column('EXTN_NUMBER', String(255)),
    Column('ADVANCE_CHECKED_IN_YN', String(255)),
    Column('SHOW_AWARDS_LAMP_YN', String(255)),
    Column('LIST_G_MEM_TYPE_LEVEL', String(255)),
    Column('LIST_G_INV_ITEMS', String(255)),
    Column('LIST_G_BILL_RESV', String(255)),
    Column('LIST_G_COMMENT_NAME_ID', String(255)),
    Column('LIST_G_RESERV_PROMO', String(255)),
    Column('LIST_G_DEPT_ID', String(255)),
    Column('LIST_G_DEP_DATE_CHANGE', String(255)),
    Column('LIST_G_COMMENT_RESV_NAME_ID', String(255)),
    Column('LIST_G_FIXED_CHARGES', String(255)),
    Column('LIST_G_AWARDS', String(255)),
    Column('NO_OF_STAYS', String(255)),
    Column('NO_OF_NIGHTS', String(255)),
    Column('COUNT_ROUTING', String(255)),
    Column('COUNT_COMMENTS', String(255)),
    Column('COUNT_RES_COMMENTS', String(255)),
    Column('COUNT_PROMOTIONS', String(255)),
    Column('COUNT_TRACES', String(255)),
    Column('COUNT_FIXED_CHARGES', String(255)),
    Column('COUNT_MEMBER_TYPE', String(255)),
    Column('COUNT_INVENTORY_ITEMS', String(255)),
    Column('COUNT_DEP_DATE_CHANGE', String(255)),
    Column('CF_COLOR_DESC', String(255)),
    Column('CF_DISPLAY_RECORD_01', String(255)),
    Column('CF_ADULTS', String(255)),
    Column('CF_CHILDREN', String(255)),
    Column('CF_NO_OF_ROOMS', String(255)),
)

synxis_cloud_reservation_model = Table(
    'synxis_cloud_reservation', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Chain', String(255)),
    Column('Brand', String(255)),
    Column('Hotel', String(255)),
    Column('Confirm_No', String(255)),
    Column('Rez_Status_Desc', String(255)),
    Column('Status_Dt', String(255)),
    Column('Guest_Nm', String(255)),
    Column('Channel_Cd', String(255)),
    Column('Sec_Channel_Desc', String(255)),
    Column('Sub_Source', String(255)),
    Column('Sub_Src_CD', String(255)),
    Column('Location', String(255)),
    Column('Arrival_Dt', String(255)),
    Column('Depart_Dt', String(255)),
    Column('Nights_Qty', String(255)),
    Column('Override_Oversell', String(255)),
    Column('Room_Qty', String(255)),
    Column('Rate_Category_Name', String(255)),
    Column('Rate_Type_Code', String(255)),
    Column('Rez_Avg_Rate_Amt', String(255)),
    Column('Onshore_Rate_Type_Code', String(255)),
    Column('Onshore_Rez_Avg_Rate_Amt', String(255)),
    Column('Room_Type_Code', String(255)),
    Column('Record_Locator', String(255)),
    Column('Booker_Loyalty_Program_Level_List', String(255)),
    Column('Loyalty_Type', String(255)),
    Column('Loyalty_Program', String(255)),
    Column('Loyalty_Number', String(255)),
    Column('Loyalty_Level_Code', String(255)),
    Column('Loyalty_Level_Name', String(255)),
    Column('Loyalty_Points_Payment', String(255)),
    Column('Payment_Typ', String(255)),
    Column('VCC_Authorization_Amount', String(255)),
    Column('VCC_Currency_Code', String(255)),
    Column('VCC_Payment_Model', String(255)),
    Column('VCC_Card_Activation_Start', String(255)),
    Column('VCC_Card_Activation_End', String(255)),
    Column('Direct_Bill_Account_Number', String(255)),
    Column('Direct_Bill_Project_Number', String(255)),
    Column('Total_Points_Pymnt', String(255)),
    Column('Points_Refund', String(255)),
    Column('Total_Cash_Pymnt', String(255)),
    Column('Pay_At_Property', String(255)),
    Column('Cash_Refund', String(255)),
    Column('Total_Price_For_Adult', String(255)),
    Column('Total_Adult_Occupancy', String(255)),
    Column('Total_Price_For_Child_Age_Group1', String(255)),
    Column('Total_Child_Occupancy_For_Age_Group1', String(255)),
    Column('Total_Price_For_Child_Age_Group2', String(255)),
    Column('Total_Child_Occupancy_For_Age_Group2', String(255)),
    Column('Total_Price_For_Child_Age_Group3', String(255)),
    Column('Total_Child_Occupancy_For_Age_Group3', String(255)),
    Column('Total_Price_For_Child_Age_Group4', String(255)),
    Column('Total_Child_Occupancy_For_Age_Group4', String(255)),
    Column('Total_Price_For_Child_Age_Group5', String(255)),
    Column('Total_Child_Occupancy_For_Age_Group5', String(255)),
    Column('Total_Price_For_Child_Unknown_Age_Group', String(255)),
    Column('Total_Child_Occupancy_For_Unknown_Age_Group', String(255)),
    Column('Share_With', String(255)),
    Column('Channel_Connect_Confirm_NO', String(255)),
    Column('PMS_Confirm_Code', String(255)),
    Column('Original_Room_Type_Code', String(255)),
    Column('Original_Rm_Typ_Nm', String(255)),
    Column('Template_Code', String(255)),
    Column('Template_Name', String(255)),
    Column('Blacklist_Reason', String(255)),
    Column('Visa_Information', String(255)),
    Column('Installment_Amount', String(255)),
    Column('Number_of_Installments', String(255)),
    Column('Interest_Amount', String(255)),
    Column('Interest_Rate_Percentage', String(255)),
    Column('Total_Installment_Amount', String(255)),
    Column('Rate_Credential_ID', String(255)),
    Column('Trace_Date', String(255)),
    Column('Trace_Completion_Flag', String(255)),
    Column('Trace_Completion_Date', String(255)),
    Column('Trace_Text', String(255)),
    Column('RM_Upgrade_Reason_CD', String(255)),
    Column('Room_Upsell', String(255)),
    Column('Room_To_Charge', String(255)),
    Column('Onhold_Duration', String(255)),
    Column('AutoCancel_ReleaseDateTime_ScheduledOrActual', String(255)),
    Column('Commission_Cd', String(255)),
    Column('Comm_Percent_Override_List', String(255)),
    Column('Coupon_Offer', String(255)),
    Column('Coupon_Discount_Total', String(255)),
    Column('Promotion', String(255)),
    Column('Promo_Discount', String(255)),
    Column('Maximum_Discount_Applied', String(255)),
    Column('Paynow_Discount', String(255)),
)

synxis_cloud_forecast_model = Table(
    'synxis_cloud_forecast', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('cal_dt', String(255)),
    Column('Total_Rooms', String(255)),
    Column('OOO_OOI', String(255)),
    Column('rentable_rooms', String(255)),
    Column('Rooms_Sold', String(255)),
    Column('total_stayovers', String(255)),
    Column('total_due_out', String(255)),
    Column('Total_Reservations', String(255)),
    Column('day_use_in_house', String(255)),
    Column('gtd', String(255)),
    Column('non_gtd', String(255)),
    Column('Not_Picked_Up', String(255)),
    Column('Left_To_Sell', String(255)),
    Column('occ_per', String(255)),
    Column('Total_Room_Revenue', String(255)),
    Column('ADR', String(255)),
    Column('Adult_Child', String(255)),
    Column('Sum_Total_Rooms', String(255)),
    Column('SumOOO_OOI', String(255)),
    Column('Sum_Rentable_Rooms', String(255)),
    Column('Sum_Rooms_Sold', String(255)),
    Column('Sum_Stayovers', String(255)),
    Column('Sum_Checkouts', String(255)),
    Column('Sum_Arrivals', String(255)),
    Column('Sum_Day_Use', String(255)),
    Column('SumGtd', String(255)),
    Column('SumNonGtd', String(255)),
    Column('Sum_GroupsRoomsNotPickedUp', String(255)),
    Column('Sum_Rooms_Left_To_Sell', String(255)),
    Column('Sum_RoomsOccupied_Percentage', String(255)),
    Column('SumTotalRoomRevenue', String(255)),
    Column('Sum_ADR', String(255)),
    Column('SUM_ADULT_CHILD', String(255)),
)

synxis_cloud_revenue_recap_model = Table(
    'synxis_cloud_revenue_recap', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Date', String(255)),
    Column('report_type', String(255)),
    Column('report_type_values', String(255)),
    Column('Room_Nights', String(255)),
    Column('Room', String(255)),
    Column('F_B', String(255)),
    Column('Taxes', String(255)),
    Column('Other', String(255)),
    Column('Month_To_Date_Room_Nights', String(255)),
    Column('Month_To_Date_Room', String(255)),
    Column('Month_To_Date_F_B', String(255)),
    Column('Month_To_Date_Taxes', String(255)),
    Column('Month_To_Date_Others', String(255)),
    Column('Year_To_Date_Room_Nights', String(255)),
    Column('Year_To_Date__Room', String(255)),
    Column('Year_To_Date_F_B', String(255)),
    Column('Year_To_Date_Taxes', String(255)),
    Column('Year_To_Date_Other', String(255)),
    Column('Room_Nights_Total', String(255)),
    Column('Room_Total', String(255)),
    Column('F_B_Total', String(255)),
    Column('Taxes_Total', String(255)),
    Column('Other_Total', String(255)),
    Column('Month_To_Date_Room_Nights_Total', String(255)),
    Column('Month_To_Date_Room_Total', String(255)),
    Column('Month_To_Date_F_B_total', String(255)),
    Column('Month_To_Date_Taxes_Total', String(255)),
    Column('Month_To_Date_Total', String(255)),
    Column('Year_To_Date_Room_Nights_Total', String(255)),
    Column('Year_To_Date_Room_Total', String(255)),
    Column('Year_To_Date_F_B_Total', String(255)),
    Column('Year_To_Date_Taxes_Total', String(255)),
    Column('Year_To_Date_Total', String(255)),
)

synxis_cloud_monthly_summary_model = Table(
    'synxis_cloud_monthly_summary', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('BUSINESS_DT', String(255)),
    Column('OCCUPIED_ROOM_QTY', String(255)),
    Column('RENTABLE_ROOM_QTY', String(255)),
    Column('OCCUPANCY_PERCENT', String(255)),
    Column('ADR_WITH_COMPS', String(255)),
    Column('TOTAL_FOOD_AND_BEV_REV', String(255)),
    Column('TOTAL_ROOM_REV1', String(255)),
    Column('TOTAL_TAX_REV', String(255)),
    Column('TOTAL_OTH_REV', String(255)),
    Column('TOTAL_REV', String(255)),
    Column('Date', String(255)),
    Column('OCCUPIED_ROOM_QTY_Total', String(255)),
    Column('RENTABLE_ROOM_QTY_Total', String(255)),
    Column('Occupancy_Percent_Total', String(255)),
    Column('ADR_Total', String(255)),
    Column('FoodandBeverage', String(255)),
    Column('RoomCharges', String(255)),
    Column('Taxes', String(255)),
    Column('Others', String(255)),
    Column('Total', String(255)),
)

marriott_reservation_model = Table(
    'marriott_reservation', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('StayYearCalendar', String(255)),
    Column('StayYYYYMM', String(255)),
    Column('CustomWDWE', String(255)),
    Column('StayDOWText', String(255)),
    Column('StayDate', String(255)),
    Column('ArrivalIndicator', String(255)),
    Column('BookingDate', String(255)),
    Column('AVPName', String(255)),
    Column('BrandName', String(255)),
    Column('HtlComparableText', String(255)),
    Column('PropertyCountryRegion', String(255)),
    Column('HotelTypeName', String(255)),
    Column('ManagementType', String(255)),
    Column('MARSHACode', String(255)),
    Column('PublicClusterName', String(255)),
    Column('GlobalRegionName', String(255)),
    Column('GlobalDivision', String(255)),
    Column('MarketCategory', String(255)),
    Column('MarketSegmentNameforReport', String(255)),
    Column('MarketPrfxNameforReport', String(255)),
    Column('RateProgramCode', String(255)),
    Column('RateProgramName', String(255)),
    Column('RateProgramTier', String(255)),
    Column('RateCategoryCode', String(255)),
    Column('MarketCode', String(255)),
    Column('OpportunityNum', String(255)),
    Column('QuoteNum', String(255)),
    Column('LengthofAccomLOA', String(255)),
    Column('LOATierID', String(255)),
    Column('NightsOut', String(255)),
    Column('NightsOutTier', String(255)),
    Column('ChannelAggregateName', String(255)),
    Column('ChannelDetailName', String(255)),
    Column('ChannelTypeName', String(255)),
    Column('ChannelSiteName', String(255)),
    Column('ChannelPartnerName', String(255)),
    Column('BookingSourceType', String(255)),
    Column('BookingOffice', String(255)),
    Column('IntermediaryTypeCode', String(255)),
    Column('Intermediary', String(255)),
    Column('RoomCategoryCode', String(255)),
    Column('RoomPoolCode', String(255)),
    Column('MARSHARateNet', String(255)),
    Column('RewardsLevelText', String(255)),
    Column('RoomNights', String(255)),
    Column('ADRNet', String(255)),
    Column('RevenueNet', String(255)),
    Column('AverageRoomNights', String(255)),
    Column('AverageRevenue', String(255)),
)

marriott_forecast_model = Table(
    'marriott_forecast', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('ArrivalDate', String(255)),
    Column('ArrivalDay', String(255)),
    Column('WEindicator', String(255)),
    Column('Capacity', String(255)),
    Column('DaysOut', String(255)),
    Column('SysRemDem', String(255)),
    Column('RemDemSTLY', String(255)),
    Column('AppliedRemDem', String(255)),
    Column('UserOverride', String(255)),
    Column('Event', String(255)),
    Column('OYv2TotalHotelOccupancy', String(255)),
    Column('TotalAvailableTransientSupply', String(255)),
    Column('TotalTransientBooked', String(255)),
    Column('TotalTransientBookedSTLY', String(255)),
    Column('AdditionalDemand', String(255)),
    Column('AdditionalDemandSTLY', String(255)),
    Column('TotalTransientDemand', String(255)),
    Column('TotalTransientDemandSTLY', String(255)),
    Column('AllotmentForecast', String(255)),
    Column('AllotmentRoomsSold', String(255)),
    Column('OutofOrder', String(255)),
    Column('GroupRoomBlockAuthorized', String(255)),
    Column('GroupBooked', String(255)),
    Column('OYv2GroupProj', String(255)),
    Column('ContractRoomBlockAuthorized', String(255)),
    Column('ContractBooked', String(255)),
    Column('OYv2ContractProj', String(255)),
    Column('ComplimentaryBookedTY', String(255)),
    Column('RemDemPremiumRetailTY', String(255)),
    Column('RemDemPremiumRetailTYPer', String(255)),
    Column('PremiumRetailTY', String(255)),
    Column('RemDemPremiumRetailSTLY', String(255)),
    Column('RemDemPremiumRetailSTLYPer', String(255)),
    Column('PremiumRetailSTLY', String(255)),
    Column('RemDemStandardRetailTY', String(255)),
    Column('RemDemStandardRetailTYPer', String(255)),
    Column('StandardRetailTY', String(255)),
    Column('RemDemStandardRetailSTLY', String(255)),
    Column('RemDemStandardRetailSTLYPer', String(255)),
    Column('StandardRetailSTLY', String(255)),
    Column('RemDemSpecialCorporateLRATY', String(255)),
    Column('RemDemSpecialCorporateLRATYPer', String(255)),
    Column('SpecialCorporateLRATY', String(255)),
    Column('RemDemSpecialCorporateLRASTLY', String(255)),
    Column('RemDemSpecialCorporateLRASTLYPer', String(255)),
    Column('SpecialCorporateLRASTLY', String(255)),
    Column('RemDemRewardRedemptionTY', String(255)),
    Column('RemDemRewardRedemptionTYPer', String(255)),
    Column('RewardRedemptionTY', String(255)),
    Column('RemDemRewardRedemptionSTLY', String(255)),
    Column('RemDemRewardRedemptionSTLYPer', String(255)),
    Column('RewardRedemptionSTLY', String(255)),
    Column('RemDemPolicyDrivenTY', String(255)),
    Column('RemDemPolicyDrivenTYPer', String(255)),
    Column('PolicyDrivenTY', String(255)),
    Column('RemDemPolicyDrivenSTLY', String(255)),
    Column('RemDemPolicyDrivenSTLYPer', String(255)),
    Column('PolicyDrivenSTLY', String(255)),
    Column('RemDemGovtMilitaryTY', String(255)),
    Column('RemDemGovtMilitaryTYPer', String(255)),
    Column('GovtMilitaryTY', String(255)),
    Column('RemDemGovtMilitarySTLY', String(255)),
    Column('RemDemGovtMilitarySTLYPer', String(255)),
    Column('GovtMilitarySTLY', String(255)),
    Column('RemDemRetailTiedDiscountTY', String(255)),
    Column('RemDemRetailTiedDiscountTYPer', String(255)),
    Column('RetailTiedDiscountTY', String(255)),
    Column('RemDemRetailTiedDiscountSTLY', String(255)),
    Column('RemDemRetailTiedDiscountSTLYPer', String(255)),
    Column('RetailTiedDiscountSTLY', String(255)),
    Column('RemDemFixedDiscountTY', String(255)),
    Column('RemDemFixedDiscountTYPer', String(255)),
    Column('FixedDiscountTY', String(255)),
    Column('RemDemFixedDiscountSTLY', String(255)),
    Column('RemDemFixedDiscountSTLYPer', String(255)),
    Column('FixedDiscountSTLY', String(255)),
    Column('RoomCollection1HurdleRevenue', String(255)),
    Column('RoomCollection1TransientOTBTY', String(255)),
    Column('RoomCollection1TransientOTBSTLY', String(255)),
    Column('RoomCollection1RemDemTY', String(255)),
    Column('RoomCollection1RemDemTYPer', String(255)),
    Column('RoomCollection1RemDemSTLY', String(255)),
    Column('RoomCollection1RemDemSTLYPer', String(255)),
    Column('RoomCollection2HurdleRevenue', String(255)),
    Column('RoomCollection2TransientOTBTY', String(255)),
    Column('RoomCollection2TransientOTBSTLY', String(255)),
    Column('RoomCollection2RemDemTY', String(255)),
    Column('RoomCollection2RemDemTYPer', String(255)),
    Column('RoomCollection2RemDemSTLY', String(255)),
    Column('RoomCollection2RemDemSTLYPer', String(255)),
)

marriott_realized_activity_model = Table(
    'marriott_realized_activity', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('ArrivalDate', String(255)),
    Column('DOW', String(255)),
    Column('EV_LO', String(255)),
    Column('TransSold', String(255)),
    Column('GroupSold', String(255)),
    Column('TotalRoomsSold_Num', String(255)),
    Column('TotalRoomsSold_Occ_Per', String(255)),
    Column('ArvlAddlDem', String(255)),
    Column('NoShows_Tran', String(255)),
    Column('NoShows_Grp', String(255)),
    Column('Cancels_TranRMS', String(255)),
    Column('Cancels_TranLOS', String(255)),
    Column('Cancels_TranTotal', String(255)),
    Column('Cancels_Grp', String(255)),
    Column('SameDayCheck_ins', String(255)),
    Column('UnexpectedStaythroughs_Tran', String(255)),
    Column('UnexpectedStaythroughs_Grp', String(255)),
    Column('EarlyCheck_outs_Tran', String(255)),
    Column('EarlyCheck_outs_Grp', String(255)),
)

marriott_total_yield_model = Table(
    'marriott_total_yield', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('Date', String(255)),
    Column('Sleeping_Room_Occ_Per', String(255)),
    Column('Function_Space_Occ_Per', String(255)),
    Column('Sleeping_Rooms_Projected', String(255)),
    Column('Transient', String(255)),
    Column('inContract', String(255)),
    Column('Definite', String(255)),
    Column('Tentative_1', String(255)),
    Column('Tentative_2', String(255)),
    Column('Hold', String(255)),
    Column('Prospect', String(255)),
    Column('To_Be_s', String(255)),
    Column('Out_of_Order_Rooms', String(255)),
    Column('MARSHA_Booked_Group', String(255)),
    Column('MARSHA_Blocked_Group', String(255)),
    Column('Group_Restrictions_Hotel', String(255)),
    Column('Restriction_Threshold_Hotel', String(255)),
)

hotelkey_occ_model = Table(
    'hotelkey_occ', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Date', String(255)),
    Column('Property', String(255)),
    Column('PFRZ', String(255)),
    Column('FRZ', String(255)),
    Column('TOD', String(255)),
    Column('DOW', String(255)),
    Column('GTD', String(255)),
    Column('LOS', String(255)),
    Column('CXL', String(255)),
    Column('OO', String(255)),
    Column('Hold', String(255)),
    Column('Yieldable', String(255)),
    Column('Sold', String(255)),
    Column('BLK', String(255)),
    Column('SD', String(255)),
    Column('OccOTB', String(255)),
    Column('OccPYClose', String(255)),
    Column('OccPYVar', String(255)),
    Column('ADROTB', String(255)),
    Column('ADRPYClose', String(255)),
    Column('ADRPYVar', String(255)),
    Column('DiscPer', String(255)),
    Column('Price1', String(255)),
    Column('LT1', String(255)),
    Column('Per1', String(255)),
    Column('RM1', String(255)),
    Column('Price2', String(255)),
    Column('LT2', String(255)),
    Column('Per2', String(255)),
    Column('RM2', String(255)),
    Column('Price3', String(255)),
    Column('LT3', String(255)),
    Column('Per3', String(255)),
    Column('RM3', String(255)),
    Column('Price4', String(255)),
    Column('LT4', String(255)),
    Column('Per4', String(255)),
    Column('RM4', String(255)),
)

hotelkey_res_model = Table(
    'hotelkey_res', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Property', String(255)),
    Column('Status', String(255)),
    Column('Channel', String(255)),
    Column('Res', String(255)),
    Column('GuestName', String(255)),
    Column('ArrivalDate', String(255)),
    Column('DepartDate', String(255)),
    Column('Nts', String(255)),
    Column('Adl', String(255)),
    Column('MarketSegment', String(255)),
    Column('Group', String(255)),
    Column('RateCode', String(255)),
    Column('Product', String(255)),
    Column('AssignedProduct', String(255)),
    Column('Rate', String(255)),
    Column('TaxInc', String(255)),
    Column('ProjectedRevenue', String(255)),
    Column('TotalWithoutTax', String(255)),
    Column('PayMth', String(255)),
    Column('PaymentsTaken', String(255)),
    Column('DepositsScheduled', String(255)),
    Column('BalanceDue', String(255)),
    Column('CreationDate', String(255)),
    Column('CreationUser', String(255)),
    Column('CP', String(255)),
    Column('CPName', String(255)),
    Column('Blank', String(255)),
)

visual_matrix_front_office_arrival_model = Table(
    'visual_matrix_front_office_arrival', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('GuestName', String(255)),
    Column('Status', String(255)),
    Column('Arrive', String(255)),
    Column('Departs', String(255)),
    Column('A', String(255)),
    Column('C', String(255)),
    Column('Type', String(255)),
    Column('Rate', String(255)),
    Column('PKG', String(255)),
    Column('MOP', String(255)),
    Column('ADV_DEP', String(255)),
    Column('Share', String(255)),
    Column('Room', String(255)),
)

visual_matrix_occupancy_model = Table(
    'visual_matrix_occupancy', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('Date', String(255)),
    Column('Day', String(255)),
    Column('Maint', String(255)),
    Column('GuestArrivals_Non_GTD', String(255)),
    Column('GuestArrivals_GTD', String(255)),
    Column('GroupArrivals_Non_GTD', String(255)),
    Column('GroupArrivals_GTD', String(255)),
    Column('GroupAlloc', String(255)),
    Column('ARV', String(255)),
    Column('Dep', String(255)),
    Column('StayOvers', String(255)),
    Column('AvailRms', String(255)),
    Column('OccRms', String(255)),
    Column('OccPer', String(255)),
    Column('RmRev', String(255)),
    Column('ADR', String(255)),
    Column('RevPar', String(255)),
    Column('ActualRoomsLY', String(255)),
    Column('OccPerVariance', String(255)),
)

bestrev_total_forecast_model = Table(
    'bestrev_total_forecast', meta,
    Column('id', Integer, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', BIGINT),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255), primary_key=True),
    Column('Alert', String(255)),
    Column('Priority', String(255)),
    Column('StayDate', String(255)),
    Column('DayofWeek', String(255)),
    Column('Favorite', String(255)),
    Column('Event', String(255)),
    Column('BestWesternRate', String(255)),
    Column('RecommendedRate', String(255)),
    Column('RatetoUpload', String(255)),
    Column('RecommendationStatus', String(255)),
    Column('MarketRate', String(255)),
    Column('AvailableRooms', String(255)),
    Column('TransientCapacity', String(255)),
    Column('TotalForecast_IncludesGroup', String(255)),
    Column('OntheBooks_IncludesGroup', String(255)),
    Column('AverageDailyRate', String(255)),
    Column('RevPAR', String(255)),
    Column('Occupancy_IncludesGroup', String(255)),
    Column('ForecastOccupancy_IncludesGroup', String(255)),
)

ideasg3_occ_model = Table(
    'ideasg3_occ', meta,
    Column('id', Integer, primary_key=True, autoincrement=True),
    Column('propertyCode', String(20)),
    Column('pullDateId', String(255)),
    Column('createdAt', TIMESTAMP(timezone=True)),
    Column('updatedAt', TIMESTAMP(timezone=True)),
    Column('createdAtEpoch', BIGINT),
    Column('updatedAtEpoch', BIGINT),
    Column('uniqueKey', String(255)),
    Column('Day_of_Week', String(255)),
    Column('Day_of_Arrival', String(255)),
    Column('Special_Event', String(255)),
    Column('Out_of_Order', String(255)),
    Column('Occupancy_On_Books_Current', String(255)),
    Column('Occupancy_On_Books_Change', String(255)),
    Column('Occupancy_Forecast_Current', String(255)),
    Column('Occupancy_Forecast_Change', String(255)),
    Column('Occupancy_Forecast_Percent_Current', String(255)),
    Column('Occupancy_Forecast_Percent_Change', String(255)),
    Column('Revenue_On_Books_USD_Current', String(255)),
    Column('Revenue_On_Books_USD_Change', String(255)),
    Column('Revenue_Forecast_USD_Current', String(255)),
    Column('Revenue_Forecast_USD_Change', String(255)),
    Column('ADR_On_Books_USD_Current', String(255)),
    Column('ADR_On_Books_USD_Change', String(255)),
    Column('ADR_Forecast_USD_Current', String(255)),
    Column('ADR_Forecast_USD_Change', String(255)),
    Column('RevPAR_On_Books_USD_Current', String(255)),
    Column('RevPAR_On_Books_USD_Change', String(255)),
    Column('RevPAR_Forecast_USD_Current', String(255)),
    Column('RevPAR_Forecast_USD_Change', String(255)),
    Column('Last_Room_Value_For_RC_DLX_USD_Current', String(255)),
    Column('Last_Room_Value_For_RC_DLX_USD_Change', String(255)),
    Column('Overbooking_Current', String(255)),
    Column('Overbooking_Change', String(255)),
    Column('BAR_by_Day_for_Room_Class_DLX_USD_Current', String(255)),
    Column('BAR_by_Day_for_Room_Class_DLX_USD_Change', String(255)),
    Column('BAR_Restricted_by_LRV_for_Room_Class_DLX_Current', String(255)),
    Column('BAR_Restricted_by_LRV_for_Room_Class_DLX_Change', String(255))

)

# meta.create_all(engine)
